name: validate

on:
  push:
  pull_request:

jobs:
  theme-component-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate about.json
        run: jq . about.json > /dev/null

      - name: Validate settings.yml
        run: ruby -e 'require "yaml"; YAML.load_file("settings.yml")'
